export const deskStructure = S =>
  S.list()
    .title('Base')
    .items([
      S.listItem()
        .title('Home & Nav Sidebar')
        .child(
          S.document()
            .title('Home & Nav Sidebar')
            .schemaType('home')
            .documentId('home'),
        ),
      S.listItem()
        .title('About')
        .child(
          S.document().title('About').schemaType('about').documentId('about'),
        ),
      S.listItem()
        .title('Links')
        .child(
          S.document().title('Links').schemaType('links').documentId('links'),
        ),
      S.listItem()
        .title('Articles')
        .child(
          S.document()
            .title('Articles')
            .schemaType('articles')
            .documentId('articles'),
        ),
      ...S.documentTypeListItems().filter(
        listItem =>
          ![
            'home',
            'nav',
            'emailForm',
            'socialPost',
            'notification',
            'details',
            'client',
            'filters',
            'link',
            'links',
            'tags',
            'about',
            'articles',
          ].includes(listItem.getId()),
      ),
    ])
